### ISSUE TITLE
KeyError loading state dict

### ISSUE THREAD

**Issue by Johnreidsilver** [DeepMed-Lab-ECNU/DeepRFT-AAAI2023#1]
Hi, running val.py I get this error:

```
Traceback (most recent call last):
  File "val.py", line 80, in <module>
    model_restoration.load_state_dict(checkpoint['params'])
KeyError: 'params'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "val.py", line 83, in <module>
    model_restoration.load_state_dict(checkpoint["state_dict"])
  File "/home/userdir/anaconda3/envs/3DP/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1672, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FMIMOUNet:
	Missing key(s) in state_dict: 
```

my conda environment is slightly different with:
Python 3.7
torch==1.13.1
cudatoolkit 10.1.243

**Comment by INVOKERer** [comment]
Sorry, this repo issue was not pushed to my mailbox. Maybe you can use https://github.com/INVOKERer/DeepRFT to reproduce this work.
